common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: tryhard
  host: localhost

development:
  <<: *common
  database: sample_app_development

test:
  <<: *common
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production
